# Generated by Django 5.1.1 on 2024-11-05 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CarroCompra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('carro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CarroCompra.carrocompra')),
            ],
        ),
    ]
