# Generated by Django 5.1.1 on 2024-11-14 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='reseñas',
        ),
        migrations.DeleteModel(
            name='Resena',
        ),
    ]
